# Generated by Django 6.0.3 on 2026-03-31 15:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixflow.departments'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 31, 15, 55, 1, 457695)),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 31, 15, 55, 1, 457711)),
        ),
    ]
