# Generated by Django 6.0.3 on 2026-04-02 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0002_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issues',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
