# Generated by Django 5.2.12 on 2026-04-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0003_alter_issues_date_created_alter_issues_date_updated'),
        ('fixflow', '0004_alter_issues_status'),
    ]

    operations = [
    ]
