# Generated by Django 5.2.12 on 2026-04-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0007_customuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
