# Generated by Django 5.2.12 on 2026-04-29 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0008_alter_customuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
