# Generated by Django 6.0.3 on 2026-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0009_alter_issues_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
