# Generated by Django 6.0.3 on 2026-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixflow', '0010_issues_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='history',
            field=models.JSONField(default=[]),
        ),
    ]
